// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "TrackSplitter",
    platforms: [.macOS("13.0")],
    products: [
        .executable(name: "tracksplitter", targets: ["TrackSplitterCLI"]),
        .executable(name: "tracksplitter-gui", targets: ["TrackSplitterGUI"])
    ],
    dependencies: [],
    targets: [
        .executableTarget(
            name: "TrackSplitterCLI",
            dependencies: ["TrackSplitterLib"],
            path: "CLI",
            sources: ["main.swift"]
        ),
        .target(
            name: "TrackSplitterLib",
            dependencies: [],
            path: "Library",
            // embed_metadata.py is a resource, not a Swift source — include it explicitly.
            resources: [
                .copy("Resources/embed_metadata.py")
            ]
        ),
        .executableTarget(
            name: "TrackSplitterGUI",
            dependencies: ["TrackSplitterLib"],
            path: "GUI",
            // Exclude XcodeGen/project artifacts; SwiftPM will still pick up .swift
            // files from the source directories even if the directories themselves
            // contain non-source files.
            exclude: [
                "project.yml",               // XcodeGen configuration
                "App/Info.plist",            // Xcode-managed app metadata
                "App/TrackSplitter.icns",    // Compiled app icon (generated by XcodeGen)
                "App/TrackSplitter.iconset"  // App icon asset catalog (generated by XcodeGen)
            ],
            sources: [
                "App",
                "Views",
                "ViewModels",
                "Models"
            ]
        ),
        .testTarget(
            name: "TrackSplitterTests",
            dependencies: ["TrackSplitterLib"],
            path: "Tests"
        )
    ]
)
